Cleaning Data

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('../../data/raw/kilang_minyak_data.csv')
df.head(10)

,conversation_id_str,created_at,favorite_count,full_text,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,reply_count,retweet_count,tweet_url,user_id_str,username
0,1975337677118710226,Mon Oct 06 23:09:36 +0000 2025,0,akubpenasaran algoritma tiktok yg 5 hatian lal...,1975337677118710226,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/197533767711871...,1962299536875077632,NaN
1,1975309495896354952,Mon Oct 06 22:32:27 +0000 2025,2,@P3gEl Pertamina jual BBM tdk ada saingan tp b...,1975328326131851296,NaN,P3gEl,in,NaN,0,0,1,https://x.com/undefined/status/197532832613185...,1395713255637585923,NaN
2,1975326330733670886,Mon Oct 06 22:24:31 +0000 2025,0,Iya dong. Jangan pake takut kualat. Selidiki j...,1975326330733670886,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/197532633073367...,81766731,NaN
3,1975320483932610931,Mon Oct 06 22:01:17 +0000 2025,0,Mungkin usia kilang-kilang minyak Pertamina su...,1975320483932610931,NaN,NaN,in,NaN,0,1,0,https://x.com/undefined/status/197532048393261...,938664737369341952,NaN
4,1975163183355539857,Mon Oct 06 20:41:56 +0000 2025,0,@Bhaktismail @tekarok007 Dan apesnya lagi sete...,1975300512053629198,NaN,Bhaktismail,in,NaN,0,0,0,https://x.com/undefined/status/197530051205362...,1591916625460334592,NaN
5,1975204096887140395,Mon Oct 06 19:46:08 +0000 2025,5,@arwidodo Dugaan : Kandungan minyak di Indones...,1975286469997830245,NaN,arwidodo,in,NaN,0,1,0,https://x.com/undefined/status/197528646999783...,1959980472836169728,NaN
6,1974636115752862004,Mon Oct 06 19:17:44 +0000 2025,0,@atasanpresidenr Emang Indonesia punya kilang ...,1975279326414422483,NaN,atasanpresidenr,in,NaN,0,0,0,https://x.com/undefined/status/197527932641442...,827721183495745536,NaN
7,1974497282964996315,Mon Oct 06 17:51:10 +0000 2025,0,@kegblgnunfaedh Ebeg kimcil kilang minyak keru...,1975257538200498411,NaN,kegblgnunfaedh,in,NaN,0,0,0,https://x.com/undefined/status/197525753820049...,1262747411547488262,NaN
8,1974698108635550045,Mon Oct 06 16:27:41 +0000 2025,0,@KangManto123 @pertamina Jangankan kilang miny...,1975236531716858193,NaN,KangManto123,in,NaN,0,0,0,https://x.com/undefined/status/197523653171685...,1672211876,NaN
9,1974698108635550045,Mon Oct 06 15:18:20 +0000 2025,0,@Novelaku1266621 @KangManto123 @pertamina Ya s...,1975219078060294298,NaN,Novelaku1266621,in,NaN,0,0,0,https://x.com/undefined/status/197521907806029...,1720665183188922368,NaN

Check Missing Value

In [4]:
df.isnull().sum()

conversation_id_str           0
created_at                    0
favorite_count                0
full_text                     0
id_str                        0
image_url                  1932
in_reply_to_screen_name    1131
lang                          0
location                   2517
quote_count                   0
reply_count                   0
retweet_count                 0
tweet_url                     0
user_id_str                   0
username                   2517
dtype: int64

In [5]:

df = df.drop(['username', 'location', 'image_url', 'in_reply_to_screen_name'], axis=1)
df.isnull().sum()

conversation_id_str    0
created_at             0
favorite_count         0
full_text              0
id_str                 0
lang                   0
quote_count            0
reply_count            0
retweet_count          0
tweet_url              0
user_id_str            0
dtype: int64

Casefolding dataset

In [6]:
df['full_text'] = df['full_text'].str.lower()
df['tweet_url'] = df['tweet_url'].str.lower()
df.head(10)

,conversation_id_str,created_at,favorite_count,full_text,id_str,lang,quote_count,reply_count,retweet_count,tweet_url,user_id_str
0,1975337677118710226,Mon Oct 06 23:09:36 +0000 2025,0,akubpenasaran algoritma tiktok yg 5 hatian lal...,1975337677118710226,in,0,0,0,https://x.com/undefined/status/197533767711871...,1962299536875077632
1,1975309495896354952,Mon Oct 06 22:32:27 +0000 2025,2,@p3gel pertamina jual bbm tdk ada saingan tp b...,1975328326131851296,in,0,0,1,https://x.com/undefined/status/197532832613185...,1395713255637585923
2,1975326330733670886,Mon Oct 06 22:24:31 +0000 2025,0,iya dong. jangan pake takut kualat. selidiki j...,1975326330733670886,in,0,0,0,https://x.com/undefined/status/197532633073367...,81766731
3,1975320483932610931,Mon Oct 06 22:01:17 +0000 2025,0,mungkin usia kilang-kilang minyak pertamina su...,1975320483932610931,in,0,1,0,https://x.com/undefined/status/197532048393261...,938664737369341952
4,1975163183355539857,Mon Oct 06 20:41:56 +0000 2025,0,@bhaktismail @tekarok007 dan apesnya lagi sete...,1975300512053629198,in,0,0,0,https://x.com/undefined/status/197530051205362...,1591916625460334592
5,1975204096887140395,Mon Oct 06 19:46:08 +0000 2025,5,@arwidodo dugaan : kandungan minyak di indones...,1975286469997830245,in,0,1,0,https://x.com/undefined/status/197528646999783...,1959980472836169728
6,1974636115752862004,Mon Oct 06 19:17:44 +0000 2025,0,@atasanpresidenr emang indonesia punya kilang ...,1975279326414422483,in,0,0,0,https://x.com/undefined/status/197527932641442...,827721183495745536
7,1974497282964996315,Mon Oct 06 17:51:10 +0000 2025,0,@kegblgnunfaedh ebeg kimcil kilang minyak keru...,1975257538200498411,in,0,0,0,https://x.com/undefined/status/197525753820049...,1262747411547488262
8,1974698108635550045,Mon Oct 06 16:27:41 +0000 2025,0,@kangmanto123 @pertamina jangankan kilang miny...,1975236531716858193,in,0,0,0,https://x.com/undefined/status/197523653171685...,1672211876
9,1974698108635550045,Mon Oct 06 15:18:20 +0000 2025,0,@novelaku1266621 @kangmanto123 @pertamina ya s...,1975219078060294298,in,0,0,0,https://x.com/undefined/status/197521907806029...,1720665183188922368

Hapus tag username untuk full text komentar

In [7]:
import re

df['full_text'] = df['full_text'].apply(lambda x: re.sub(r'@\w+', '', str(x)))

df['full_text'] = df['full_text'].str.replace('\s', '', regex=True).str.strip()

df.head(10)

,conversation_id_str,created_at,favorite_count,full_text,id_str,lang,quote_count,reply_count,retweet_count,tweet_url,user_id_str
0,1975337677118710226,Mon Oct 06 23:09:36 +0000 2025,0,akubpenasaranalgoritmatiktokyg5hatianlalusoalk...,1975337677118710226,in,0,0,0,https://x.com/undefined/status/197533767711871...,1962299536875077632
1,1975309495896354952,Mon Oct 06 22:32:27 +0000 2025,2,pertaminajualbbmtdkadasaingantpboncosmelulupej...,1975328326131851296,in,0,0,1,https://x.com/undefined/status/197532832613185...,1395713255637585923
2,1975326330733670886,Mon Oct 06 22:24:31 +0000 2025,0,iyadong.janganpaketakutkualat.selidikijugasemu...,1975326330733670886,in,0,0,0,https://x.com/undefined/status/197532633073367...,81766731
3,1975320483932610931,Mon Oct 06 22:01:17 +0000 2025,0,mungkinusiakilang-kilangminyakpertaminasudahtu...,1975320483932610931,in,0,1,0,https://x.com/undefined/status/197532048393261...,938664737369341952
4,1975163183355539857,Mon Oct 06 20:41:56 +0000 2025,0,danapesnyalagisetelahkerajaansaudimembatalkani...,1975300512053629198,in,0,0,0,https://x.com/undefined/status/197530051205362...,1591916625460334592
5,1975204096887140395,Mon Oct 06 19:46:08 +0000 2025,5,dugaan:kandunganminyakdiindonesiabanyaktpminya...,1975286469997830245,in,0,1,0,https://x.com/undefined/status/197528646999783...,1959980472836169728
6,1974636115752862004,Mon Oct 06 19:17:44 +0000 2025,0,emangindonesiapunyakilangminyakterakhirmasihja...,1975279326414422483,in,0,0,0,https://x.com/undefined/status/197527932641442...,827721183495745536
7,1974497282964996315,Mon Oct 06 17:51:10 +0000 2025,0,ebegkimcilkilangminyakkerupuktengirimendoan,1975257538200498411,in,0,0,0,https://x.com/undefined/status/197525753820049...,1262747411547488262
8,1974698108635550045,Mon Oct 06 16:27:41 +0000 2025,0,jangankankilangminyakpasarajakalomaupembaruand...,1975236531716858193,in,0,0,0,https://x.com/undefined/status/197523653171685...,1672211876
9,1974698108635550045,Mon Oct 06 15:18:20 +0000 2025,0,yasecarateorikebakarankilangminyakbisamenguntu...,1975219078060294298,in,0,0,0,https://x.com/undefined/status/197521907806029...,1720665183188922368